
        include:
          
          - board: nice_nano_v2 # Sau ce placă nRF52840 Pro Micro folosești (ex: 'nice_nano' dacă e v1)
            shield: ciupitu_stefan # Numele shield-ului tău (cel mic, din Kconfig.shield)
            snippet: zmk-usb-logging

