name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    secrets: inherit # Această linie permite workflow-ului ZMK să acceseze secrete, dacă e necesar
    with:
      # Aici specifici ce combinații de placă (board) și shield vrei să construiești.
      # Formatul este un string JSON.
      include: |
        [
          {
            "board": "nice_nano_v2", # Sau "nice_nano" dacă placa ta este v1 sau un alt nRF52840 Pro Micro compatibil.
                                     # Verifică identificatorul ZMK corect pentru placa ta exactă.
            "shield": "ciupitu_stefan"
          }
        ]
      # Dacă ai nevoie de argumente speciale pentru comanda west, le poți adăuga aici, de exemplu:
      # west_args: "-p" # Curăță build-ul anterior înainte de a începe unul nou
