name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Apelăm direct workflow-ul reutilizabil ZMK
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    secrets: inherit # Permite workflow-ului ZMK să acceseze secrete, dacă e necesar
    with:
      # Aici pasăm întreaga listă de combinații placă/shield ca un string JSON
      # către inputul 'matrix' definit în build-user-config.yml
      matrix: |
        [
          {
            "board": "nice_nano_v2", # Sau "nice_nano" sau identificatorul corect pentru placa ta nRF52840 Pro Micro
            "shield": "ciupitu_stefan"
          }
          # Dacă vrei să adaugi și alte build-uri în viitor, le adaugi aici ca alte obiecte JSON,
          # separate prin virgulă, în interiorul array-ului [...]. De exemplu:
          # ,
          # {
          #   "board": "alt_board_id",
          #   "shield": "alt_shield_id"
          # },
          # {
          #   "board": "nice_nano_v2",
          #   "shield": "settings_reset"
          # }
        ]
      # Poți adăuga și alte inputuri definite de build-user-config.yml aici, dacă e necesar.
      # De exemplu, pentru a curăța build-ul anterior:
      # west_args: "-p"
